settings: &settings
  moods: &moods
    label: Mood options
    value: 'lawbreaker, social, adventurous, energetic, intellectual, romantic, relaxed, lonely'
    editable: true
    deletable: false
    typecast: TranslatedHashTypecaster
    validations:
      presence: true
      
  categories: &categories
    label: Category options
    value: 'food, healthy_life, culture, music, drinks, have_a_stroll, shopping, alternative'
    editable: true
    deletable: false
    typecast: TranslatedHashTypecaster
    validations:
      presence: true

development:
  <<: *settings  

test:
  <<: *settings

production:
  <<: *settings
