settings: &settings
  moods: &moods
    label: Mood options
    value: 'Illegal, Sociable, Adventure, Active, Cultural, Romantic, Relaxed, Solitary'
    editable: true
    deletable: false
    validations:
      presence: true
      
  categories: &categories
    label: Category options
    value: 'Eat, Drink, Healthy Life, Culture, Shopping, Dancing, Live Music, Walks'
    editable: true
    deletable: false
    validations:
      presence: true

development:
  <<: *settings  
  google_analytics_key:
    <<: *google
    label: Development Google analytics key
    value: 'UA-xxxxxx-1'

test:
  <<: *settings

production:
  <<: *settings
